# Generated by Django 5.0.1 on 2026-01-06 22:23

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BlacklistEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        db_index=True,
                        help_text="Contract address (0x...)",
                        max_length=42,
                        unique=True,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("DRAINER", "Token Drainer"),
                            ("SCAM", "Scam Contract"),
                            ("PHISHING", "Phishing"),
                            ("EXPLOIT", "Known Exploit"),
                            ("UNKNOWN", "Unknown Malicious"),
                        ],
                        default="UNKNOWN",
                        max_length=20,
                    ),
                ),
                (
                    "severity",
                    models.IntegerField(
                        default=50, help_text="Risk points to add (0-100)"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="Known name of the contract/scam",
                        max_length=255,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        blank=True,
                        help_text="Source of blacklist entry (e.g., ChainAbuse, manual)",
                        max_length=255,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name_plural": "Blacklist entries",
                "db_table": "blacklist_entries",
                "ordering": ["-severity", "-added_at"],
            },
        ),
    ]
