# Generated by Django 5.0.1 on 2026-01-06 22:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("scans", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Approval",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token_address", models.CharField(db_index=True, max_length=42)),
                (
                    "token_type",
                    models.CharField(
                        choices=[
                            ("ERC20", "ERC20"),
                            ("ERC721", "ERC721"),
                            ("ERC1155", "ERC1155"),
                            ("UNKNOWN", "UNKNOWN"),
                        ],
                        max_length=10,
                    ),
                ),
                ("spender_address", models.CharField(db_index=True, max_length=42)),
                (
                    "approved_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        help_text="Approved amount (null for NFTs)",
                        max_digits=78,
                        null=True,
                    ),
                ),
                ("is_unlimited", models.BooleanField(default=False)),
                (
                    "is_operator",
                    models.BooleanField(
                        default=False, help_text="For NFT approveForAll"
                    ),
                ),
                ("risk_points", models.IntegerField(default=0)),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("LOW", "LOW"),
                            ("MEDIUM", "MEDIUM"),
                            ("HIGH", "HIGH"),
                            ("CRITICAL", "CRITICAL"),
                        ],
                        default="LOW",
                        max_length=20,
                    ),
                ),
                (
                    "risk_reasons",
                    models.JSONField(
                        default=list, help_text="List of risk reason strings"
                    ),
                ),
                ("block_number", models.BigIntegerField(blank=True, null=True)),
                ("transaction_hash", models.CharField(blank=True, max_length=66)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "wallet_scan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approvals",
                        to="scans.walletscan",
                    ),
                ),
            ],
            options={
                "db_table": "approvals",
                "indexes": [
                    models.Index(
                        fields=["wallet_scan", "risk_level"],
                        name="approvals_wallet__d10adf_idx",
                    ),
                    models.Index(
                        fields=["spender_address"], name="approvals_spender_013a4e_idx"
                    ),
                    models.Index(
                        fields=["token_address"], name="approvals_token_a_be1458_idx"
                    ),
                ],
            },
        ),
    ]
