# Generated by Django 5.0.1 on 2026-01-06 22:23

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Wallet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        db_index=True,
                        help_text="Ethereum wallet address (0x...)",
                        max_length=42,
                        unique=True,
                    ),
                ),
                (
                    "chain_id",
                    models.IntegerField(default=1, help_text="Blockchain network ID"),
                ),
                ("first_scanned_at", models.DateTimeField(auto_now_add=True)),
                ("last_scanned_at", models.DateTimeField(auto_now=True)),
                ("total_scans", models.IntegerField(default=0)),
            ],
            options={
                "db_table": "wallets",
                "indexes": [
                    models.Index(
                        fields=["address", "chain_id"],
                        name="wallets_address_0531ff_idx",
                    )
                ],
            },
        ),
    ]
