# Generated by Django 5.0.1 on 2026-01-06 22:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("wallets", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WalletScan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("total_approvals", models.IntegerField(default=0)),
                ("total_risk_score", models.IntegerField(default=0)),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("LOW", "LOW"),
                            ("MEDIUM", "MEDIUM"),
                            ("HIGH", "HIGH"),
                            ("CRITICAL", "CRITICAL"),
                        ],
                        default="LOW",
                        max_length=20,
                    ),
                ),
                ("high_risk_count", models.IntegerField(default=0)),
                ("critical_risk_count", models.IntegerField(default=0)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scans",
                        to="wallets.wallet",
                    ),
                ),
            ],
            options={
                "db_table": "wallet_scans",
                "ordering": ["-started_at"],
                "indexes": [
                    models.Index(
                        fields=["wallet", "-started_at"],
                        name="wallet_scan_wallet__9d0625_idx",
                    ),
                    models.Index(
                        fields=["status"], name="wallet_scan_status_3769be_idx"
                    ),
                ],
            },
        ),
    ]
